# Generated by Django 5.2.4 on 2025-07-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creacion',
            new_name='fecha_publicacion',
        ),
    ]
