# Generated by Django 5.2.4 on 2025-07-24 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_rename_fecha_comentario_fecha_publicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comentarios_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
