# Generated by Django 5.2.4 on 2025-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_comentario_contenido_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='contenido',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts_imagenes/'),
        ),
    ]
